#### Import the Numpy module

In [1]:
# Typicallly,
import numpy as np
# then we could access Numpy objects using np.X
# Also we could import Numpy into the current namespace, then we use the objects as if they were built-in
# from numpy import *

#### Arrays: Similar to lists in python, except that every element of an array must be of the same type, typically a numeric type like float or int

_array_: two arguments: the list to be converted into the array and the type of each member of the list

In [2]:
a = np.array([1, 4, 5, 8], float)

Arrays can be multidimensional. Different axes are accessed using commas inside bracket notation

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a[0, 0]

1.0

Array slicing works with multiple dimensions in the same way as usual, use a single":"in a dimension indicates the use of everything along that dimension

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a[1, :])
print(a[:, 2])
print(a[-1:, -2:])

[ 4.  5.  6.]
[ 3.  6.]
[[ 5.  6.]]


The _shape_ property of an array returns a tuple with the size of each array dimension  
The _len_ function returns the length of the first axis

In [13]:
print(a.shape)
print(len(a))

(2, 3)
2


The _dtype_ property returns the type of values are stored by the array  
**float64**: similar to float in python

In [11]:
a.dtype

dtype('float64')

Similar to list, the _in_ statement can be used to test if values are present in an array

In [14]:
2 in a

True

Arrays can be reshaped using tuples that specify new dimensions

In [17]:
a = np.array(range(10), int)
print(a)
a = a.reshape((5, 2))
print(a)
print(a.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


**Python's name-binding approach still applies to arrays**  
The _copy_ function can be used to create a new, separate copy of an array

In [18]:
a = np.array([1, 2, 3], int)
b = a
c = a.copy()
b[0] = 0 # or a[0] = 0
print(a)
print(b)
print(c)

[0 2 3]
[0 2 3]
[1 2 3]


Convert array to python list

In [20]:
a = np.array([1, 2, 3], float)
a.tolist()
list(a) # same to the above

[1.0, 2.0, 3.0]

Convert the array into a binary string: _tostring_  
Create an array from this kind of binary string: __fromstring_  
These routines are convenient for saving large amount of array data in files

In [23]:
a = np.array([1, 2, 3], float)
s = a.tostring()
np.fromstring(s)

array([ 1.,  2.,  3.])

Can fill an array with a single value

In [24]:
a = np.array(range(10), float)
a.fill(0)
a

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Transpose array

In [27]:
a = np.array(range(6), float).reshape((2, 3))
print(a)
a.transpose()

[[ 0.  1.  2.]
 [ 3.  4.  5.]]


array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

Transfer multiple dimensional arrays into one-dimensional version

In [30]:
a = np.array(range(6), float).reshape((2, 3))
print(a)
a.flatten()

[[ 0.  1.  2.]
 [ 3.  4.  5.]]


array([ 0.,  1.,  2.,  3.,  4.,  5.])

Two or more arrays can be concatenated together using _concatenate_ function  
I test that when the types of the elements in the arrays are different, after concatenate, int convert to float

In [33]:
a = np.array(range(4), float)
b = np.array([[5, 6], [7, 9]], float).flatten()
c = np.array([1, 2], float)
np.concatenate((a, b, c))

array([ 0.,  1.,  2.,  3.,  5.,  6.,  7.,  9.,  1.,  2.])

If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. (Default is the first axis)

In [38]:
a = np.array(range(4), float).reshape((2, 2))
b = np.array([[5, 6], [7, 9]], float)
c = np.array([[1, 2],[8, 0]], float)
print(np.concatenate((a, b, c)))
print(np.concatenate((a, b, c), axis=0))
print(np.concatenate((a, b, c), axis=1))

[[ 0.  1.]
 [ 2.  3.]
 [ 5.  6.]
 [ 7.  9.]
 [ 1.  2.]
 [ 8.  0.]]
[[ 0.  1.]
 [ 2.  3.]
 [ 5.  6.]
 [ 7.  9.]
 [ 1.  2.]
 [ 8.  0.]]
[[ 0.  1.  5.  6.  1.  2.]
 [ 2.  3.  7.  9.  8.  0.]]


The dimensionality of an array can be increased using _newaxis_ constant in bracket notation

In [63]:
a = np.array([1, 2, 3], float)
print(a.shape)
print(a[:, np.newaxis]) # This is two dimensions, a.transpose().shape is (3,) is one-dimensional
print(a[:, np.newaxis].shape)
print(a[np.newaxis,:])
a[np.newaxis,:].shape

(3,)
[[ 1.]
 [ 2.]
 [ 3.]]
(3, 1)
[[ 1.  2.  3.]]


(1, 3)

#### Other ways to create arrays

_arange_ function is similar to _range_ but returns an array

In [66]:
np.arange(5, dtype=float)
np.arange(1, 7, 2, dtype=int)

array([1, 3, 5])

_zeros_ and _ones_ create new arrays of specified dimensions filled with 0 or 1

In [67]:
np.ones((2, 3), dtype=float)
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

**zeros_like** and **ones_like** functions create a new array (filled with 0 or 1) with the same dimensions and type of an existing one

In [68]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
np.zeros_like(a)
np.ones_like(a)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

##### Create special matrices (2D arrays)

Create an identity matrix of a given size

In [69]:
np.identity(4, dtype=float)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

_eye_ function returns matrices with ones along the kth diagonal

In [70]:
np.eye(4, k=1, dtype=float)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

#### Array mathematics

During adding, substraction, etc, the sizes of the arrays should be the same  

In [7]:
a = np.array([1, 2, 3], float)
b = np.array([4, 5, 6], float)
a + b
a - b
a / b
a % b
b ** a


array([[ -1.,   4.],
       [  1.,   6.],
       [  3.,   8.],
       [  5.,  10.],
       [  7.,  12.]])

For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication

In [3]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[2, 0], [1, 3]], float)
a * b

array([[  2.,   0.],
       [  3.,  12.]])

Errors are thrown if arrays do not match in size.  
However, arrays that do not match in the number of dimensions will be broadcasted by python ( The smaller array will be repeated as necessary to perform the operation indicated)

In [8]:
# Error
a = np.array([1, 2, 3], float)
b = np.array([2, 3], float)
# a + b

# diff # of dimensionality
a = np.array(range(10), float).reshape((5, 2))
b = np.array([-1, 3], float)
# b was broadcasted as array([[-1, 3], [-1, 3],...], float)
a + b

array([[ -1.,   4.],
       [  1.,   6.],
       [  3.,   8.],
       [  5.,  10.],
       [  7.,  12.]])

Sometimes, how we should broadcast is ambiguous, in these cases, we can use _newaxis_ constant to specify how we want to broadcast

In [9]:
a = np.zeros((2, 2), float)
b = np.array([-1, 3], float)
a + b
a + b[np.newaxis,:]
a + b[:, np.newaxis]

array([[-1., -1.],
       [ 3.,  3.]])

NumPy offers a large library of common mathematical functions that can be applied elementwise to arrays. Among these are the functions: _abs_, _sign_, _sqrt_, _log_, _log10_, _exp_, _sin_, _cos_, _tan_, _arcsin_, _arccos_, _arctan_, _sinh_, _cosh_, _tanh_, _arcsinh_, _arccosh_, and _arctanh_.

In [10]:
a = np.array([1, 4, 9], float)
np.sqrt(a)

array([ 1.,  2.,  3.])

The functions _floor_, _ceil_, and _rint_ give the lower, upper, or nearest (rounded) integer:

In [11]:
a = np.array([1.1, 1.5, 1.9], float)
np.floor(a)
np.ceil(a)
np.rint(a)

array([ 1.,  2.,  2.])

Also, _pi_ and _e_ are included in numpy

In [12]:
np.pi
np.e

2.718281828459045

#### Array Iteration

In [15]:
a = np.array([1, 4, 5], int)
for x in a:
    print(x)
a = np.arange(1, 7, dtype=int).reshape((3, 2))
for x in a:
    print(x)
for (x, y) in a:
    print(x * y)

1
4
5
[1 2]
[3 4]
[5 6]
2
12
30


#### Basic array operations

Sum an array or multiply an array

In [17]:
a = np.array([2, 4, 3], float)
a.sum()
a.prod()

# Or
np.sum(a)
np.prod(a)

24.0

Statistics of an array

In [18]:
a = np.array([2, 4, 3], float)
a.mean()
a.var()
a.std()
a.min()
a.max()

4.0

The _argmin_ and _argmax_ functions return the array indices of the minand max values

In [19]:
a = np.array([2, 4, 3], float)
a.argmax()
a.argmin()

0

For multidimensional arrays, these functions could take an optional argument _axis_ to indicate with dimension to perform them

In [25]:
a = np.arange(8, dtype=float).reshape((4, 2))
a.mean(axis=0)
a.std(axis=1)

array([ 0.5,  0.5,  0.5,  0.5])

_sort_ arrays

In [30]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a) # return to a list
a.sort() # sort the array, change the order of the element yet, but return nothing

array([-1.,  0.,  2.,  5.,  6.])

Values in an array can be clipped to be within a prespecified range  
Same as applying _min(max(x, minval), maxval)_ to each element x in an array

In [33]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([ 5.,  2.,  5.,  0.,  0.])

Extract unique element

In [34]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([ 1.,  4.,  5.,  7.])

For 2D arrays (Matrices), the diagonal can be extracted

In [35]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([ 1.,  4.])

#### Comparison operators and value testing